# streamlit_app.py
import streamlit as st
from crewai import Agent, Task, Crew, Process
from crewai_tools import SerperDevTool, WebsiteSearchTool, FileReadTool, CodeInterpreterTool
from langchain_openai import ChatOpenAI
import os

# ====================== إعداد الصفحة ======================
st.set_page_config(page_title="وكيل الذكاء الاصطناعي", page_icon="🤖", layout="wide")
st.title("🤖 وكيل الذكاء الاصطناعي المتكامل")
st.caption("Multi-Agent System - جاهز للاستخدام")

# ====================== الـ Sidebar ======================
with st.sidebar:
    st.header("الإعدادات")
        api_key = st.text_input("OpenAI API Key", type="password")
            model_name = st.selectbox("الموديل", ["gpt-4o", "gpt-4o-mini", "gpt-4-turbo"])
                
                    if api_key:
                            os.environ["OPENAI_API_KEY"] = api_key

                            # ====================== بناء الوكلاء ======================
                            @st.cache_resource
                            def create_crew(api_key, model_name):
                                if not api_key:
                                        return None
                                            
                                                llm = ChatOpenAI(model=model_name, temperature=0.2)
                                                    
                                                        search_tool = SerperDevTool() if os.getenv("SERPER_API_KEY") else None
                                                            tools = [WebsiteSearchTool(), FileReadTool(), CodeInterpreterTool()]
                                                                if search_tool:
                                                                        tools.insert(0, search_tool)

                                                                            manager = Agent(
                                                                                    role="المدير",
                                                                                            goal="توزيع المهام وتحقيق أفضل نتيجة ممكنة",
                                                                                                    backstory="مدير محترف ومنظم جدًا",
                                                                                                            allow_delegation=True,
                                                                                                                    llm=llm,
                                                                                                                            verbose=False
                                                                                                                                )

                                                                                                                                    researcher = Agent(
                                                                                                                                            role="باحث",
                                                                                                                                                    goal="البحث عن معلومات دقيقة من الإنترنت",
                                                                                                                                                            backstory="باحث خبير",
                                                                                                                                                                    tools=tools,
                                                                                                                                                                            llm=llm,
                                                                                                                                                                                    verbose=False
                                                                                                                                                                                        )

                                                                                                                                                                                            coder = Agent(
                                                                                                                                                                                                    role="مطور",
                                                                                                                                                                                                            goal="كتابة وتعديل الكود",
                                                                                                                                                                                                                    backstory="مطور سينيور",
                                                                                                                                                                                                                            tools=tools,
                                                                                                                                                                                                                                    llm=llm,
                                                                                                                                                                                                                                            verbose=False
                                                                                                                                                                                                                                                )

                                                                                                                                                                                                                                                    analyst = Agent(
                                                                                                                                                                                                                                                            role="محلل",
                                                                                                                                                                                                                                                                    goal="تحليل المعلومات واستخراج الرؤى",
                                                                                                                                                                                                                                                                            backstory="محلل بيانات محترف",
                                                                                                                                                                                                                                                                                    llm=llm,
                                                                                                                                                                                                                                                                                            verbose=False
                                                                                                                                                                                                                                                                                                )

                                                                                                                                                                                                                                                                                                    writer = Agent(
                                                                                                                                                                                                                                                                                                            role="كاتب",
                                                                                                                                                                                                                                                                                                                    goal="كتابة محتوى احترافي وواضح",
                                                                                                                                                                                                                                                                                                                            backstory="كاتب محترف",
                                                                                                                                                                                                                                                                                                                                    llm=llm,
                                                                                                                                                                                                                                                                                                                                            verbose=False
                                                                                                                                                                                                                                                                                                                                                )

                                                                                                                                                                                                                                                                                                                                                    return manager, researcher, coder, analyst, writer, llm

                                                                                                                                                                                                                                                                                                                                                    # ====================== الواجهة ======================
                                                                                                                                                                                                                                                                                                                                                    if not api_key:
                                                                                                                                                                                                                                                                                                                                                        st.warning("حط الـ OpenAI API Key في الـ Sidebar عشان تشتغل")
                                                                                                                                                                                                                                                                                                                                                            st.stop()

                                                                                                                                                                                                                                                                                                                                                            manager, researcher, coder, analyst, writer, llm = create_crew(api_key, model_name)

                                                                                                                                                                                                                                                                                                                                                            # شات
                                                                                                                                                                                                                                                                                                                                                            if "messages" not in st.session_state:
                                                                                                                                                                                                                                                                                                                                                                st.session_state.messages = []

                                                                                                                                                                                                                                                                                                                                                                for message in st.session_state.messages:
                                                                                                                                                                                                                                                                                                                                                                    with st.chat_message(message["role"]):
                                                                                                                                                                                                                                                                                                                                                                            st.markdown(message["content"])

                                                                                                                                                                                                                                                                                                                                                                            if prompt := st.chat_input("اكتب المهمة اللي عايز الوكيل ينفذها..."):
                                                                                                                                                                                                                                                                                                                                                                                st.session_state.messages.append({"role": "user", "content": prompt})
                                                                                                                                                                                                                                                                                                                                                                                    with st.chat_message("user"):
                                                                                                                                                                                                                                                                                                                                                                                            st.markdown(prompt)

                                                                                                                                                                                                                                                                                                                                                                                                with st.chat_message("assistant"):
                                                                                                                                                                                                                                                                                                                                                                                                        with st.spinner("الوكلاء بيشتغلوا دلوقتي..."):
                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                # إنشاء المهام حسب طلب المستخدم
                                                                                                                                                                                                                                                                                                                                                                                                                                            task = Task(
                                                                                                                                                                                                                                                                                                                                                                                                                                                            description=prompt,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            expected_output="إجابة واضحة وكاملة بالعربية",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            agent=manager
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    crew = Crew(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    agents=[manager, researcher, coder, analyst, writer],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    tasks=[task],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    process=Process.hierarchical,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    manager_llm=llm,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    verbose=False
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            result = crew.kickoff()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        response = str(result)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                st.markdown(response)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            st.session_state.messages.append({"role": "assistant", "content": response})
                                                                                                                                                                                                                                                                                                                                                                                                                                            